id: IA5A85604
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:10:16+00:00'
last_modified: '2022-06-08T01:47:47.045739+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10345
  title: ངོར་པའི་ཆོས་འབྱུང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FDFC:
      image_group_id: I1CZ41
      title: ''
      total_pages: 460
      order: 1
      base_file: FDFC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
