id: P004539
initial_creation_type: ocr
source_metadata:
  id: bdr:W10345
  title: ངོར་པའི་ཆོས་འབྱུང
  author: ''
  volumes:
    1a96c49ea0f74abc96f52cd551b0c8d5:
      image_group_id: I1CZ41
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
